name: common_dependency
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nav_list: ^0.0.1
  env: ^0.0.1
  network: ^0.0.1
  components: ^0.0.1

  loader_overlay: ^2.2.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.5.4
  formz: ^0.4.1
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  go_router: ^13.0.0
  get_it: ^7.2.0
  conditional_wrap: ^3.0.0
  styled_text: ^8.1.0
  blur: ^3.1.0
  lifecycle: ^0.8.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.7.0
  scroll_shadow_container: ^2.1.1+2
  clipboard: ^0.1.3
  flutter_udid: ^3.0.0
  collection: ^1.17.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  mask_text_input_formatter: ^2.9.0
  permission_handler: ^10.4.5
  logger: ^2.3.0
  visibility_detector: ^0.4.0+2
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  auto_size_text: ^3.0.0
  synchronized: ^3.0.0
  dio: ^5.7.0
  internet_connection_checker_plus : ^2.2.0
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: 9.1.0
  test: ^1.21.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
